### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [AltyOfficial/MoviesAsyncApi#39]
Отличная работа! Вы мололцы! Предложения по доработке:

1. [Тут](https://github.com/AltyOfficial/MoviesAsyncApi/blob/main/src/tests/functional/utils/parametrize.py)  для статусов почему то где то применяете HTTPStatus, а где то просто [200](https://github.com/AltyOfficial/MoviesAsyncApi/blob/main/src/tests/functional/utils/parametrize.py#L32) пишете. Давайте везде сделаем HTTPStatus
2. С развитием проекта в тестах фикстур будет все больше и больше, и их нужно систематизировать. Можно вынести в отдельный файл (затем добавлять другие файлы, логически разделяя их) и тем самым облегчим [[conftest.py](http://conftest.py/)](http://conftest.py/). Для этого есть [[pytest_plugins](https://docs.pytest.org/en/latest/how-to/fixtures.html)](https://docs.pytest.org/en/latest/how-to/fixtures.html)
3. Неплохо было бы также тестировать на 400 ошибки. Отправлять запрос с данными, которые не должны пройти валидацию и проверять что ответ от сервера 400 (запрос не прошел).
4. В скриптах ожидания ES и Redis в тестах вместо вечного цикла, в который можно попасть при возникновении сложностей, лучше использовать backoff из прошлых спринтов. Он более функционален в сравнении с вечным циклом, теоретически он может сигнализировать команде поддержки после определенного количества попыток.
5. В docker-compose.yml много лишних портов выставлено наружу, достаточно только nginx. Для безопасности приложения это плохо.
6. [Этот](https://github.com/AltyOfficial/MoviesAsyncApi/blob/main/src/tests/functional/src/test_film.py#L14) маркер можно указать один раз на уровне файла: https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.20.2/
7. По SOLID лучше избавиться от упоминаний конкретных движков elastic, redis в [классах с бизнес логикой](https://github.com/AltyOfficial/MoviesAsyncApi/blob/main/src/services/film.py#L138). Для них это search_engine и cache соответственно. В данном случае можно просто именования заменить. Чтобы потом при переходе на другой движок не пришлось менять что-то в бизнес логике. Тут конечно совсем не критично, но все же.

**Comment by AltyOfficial** [comment]
[Review Pull Request](https://github.com/AltyOfficial/MoviesAsyncApi/pull/40)
